### ISSUE TITLE
Test suite will not pass

### ISSUE THREAD

**Issue by TheChymera** [pauldmccarthy/fsleyes-widgets#1]
I get a lot of [assertion errors when running the test suite](http://bpaste.net/show/6dabd84bb9cb). Can you help me out?

**Comment by pauldmccarthy** [comment]
Hey @TheChymera, I am on holiday right now - will be back at my laptop next week!

**Comment by TheChymera** [comment]
Somewhat different errors crop up [on Python 3.6](https://bpaste.net/show/0383431b4436).

**Comment by pauldmccarthy** [comment]
Looks like there are two classes of errors:
 - some `colourbarbitmap` errors are failing. I'd need to see the generated images that caused these failures to tell what is going on. 

 - Some other simulated GUI tests are failing. Are you running this on a machine with a display? Or via `xvfb-run` or some other display emulation? What back-end are you using for wxPython - `gtk2` or `gtk3`? I only test against `gtk2`, so if you're using `gtk3` that could be the problem. The `UIActionSimulator` provided by `wxPython` is extremely flaky, and not particularly consistent across platforms/backends.

**Comment by pauldmccarthy** [comment]
I encountered the same `colourbarbitmap` errors on a centos6 derived CI environment. It looks like the font rendering is slightly different from the benchmark images (probably due to different versions of libfreetype), which is causing the tests to fail. I've released 0.6.5 which makes the image comparison a bit more lenient, so this should fix the `colourbarbitmap` errors.

**Comment by TheChymera** [comment]
@pauldmccarthy thank you for the update, this indeed shows no more colourbarbitmap errors. However the previous 18 failed tests, now are replaced with 23 failed tests in `0.6.5`: https://bpaste.net/show/b3333c40afa9

Any idea about any of these?

All but one (a `TypeError`) are `AssertionErrors`, which makes me think these might also be tests which are not very robust.

**Comment by pauldmccarthy** [comment]
No, they're not robust - see my previous comment. Are you using `gtk2` or `gtk3`?

**Comment by pauldmccarthy** [comment]
I've avoided moving to gtk3 because I had loads of problems (both programmatic and visual) with it. I intend to stay with gtk2 for as long as I possibly can. When I'm forced to switch to gtk3, I will update the code and tests so that they pass (at which point I'm sure that they'll start failing on gtk2).

**Comment by TheChymera** [comment]
@pauldmccarthy hi again. I packaged the newest release (`0.8.4`) and notice the tests continue to fail, more specifically, these (full [build.log](https://github.com/pauldmccarthy/fsleyes-widgets/files/4071901/build.log)):

```
95:tests/test_floatslider.py::test_FloatSlider_mouse_non_gtk FAILED                                  [ 25%]
96:tests/test_floatslider.py::test_FloatSlider_mouse_gtk FAILED                                      [ 26%]
102:tests/test_floatslider.py::test_SliderSpinPanel_events FAILED                                     [ 31%]
131:tests/test_notebook.py::test_event FAILED                                                         [ 53%]
144:tests/test_rangeslider.py::test_RangePanel_events_slider FAILED                                   [ 64%]
147:tests/test_rangeslider.py::test_RangeSliderSpinPanel_onchange FAILED                              [ 66%]
```

The first two are GTK-related, as we discussed before, can you confirm this is the case for all of them?

**Comment by pauldmccarthy** [comment]
What is the size of your xvfb screen? Some tests may be failing because the screen is too small, and the widgets are not being rendered correctly. I use `xvfb-run -a -s "-screen 0 1920x1200x24" ...`

**Comment by TheChymera** [comment]
@pauldmccarthy hm, my parameters are `xvfbargs="-screen 0 1280x1024x24 +extension RANDR"`, sadly they are hard-coded in the utilities of my distribution, so I have do hack that before I can test with anything else. Is `1280x1024` really inappropriately low? :-/

**Comment by pauldmccarthy** [comment]
`1280x1024` should be large enough, but the situation is further confounded by the fact that these tests are not particularly robust due to the inconsistent behaviour of the `wx.UIActionSimulator` (used to simulate keyboard/mouse events). In some environments simulated mouse events work, and in other environments they don't. 

I spent some time a few months back modifying various tests so that, instead of relying on simulated events triggered by the `UIActionSimulator`, they simply programmatically call the relevant event handler function/method. Hacky, but works every time and in every environment, unlike the `UIActionSimulator`.

However, until I port *all* of the tests to work in this way (low priority for me, until they start failing on my CI rig and interrupting my own workflow), you're going to continue to run into sporadic failures. So I would recommend not wasting any time on this, and just ignoring or disabling the tests. The same goes for pauldmccarthy/fsleyes-props#1

**Comment by TheChymera** [comment]
@pauldmccarthy thanks for the clarification, yes, that what I was doing, I just wanted to document this so that it's reported :)
